etcd:
  endpoints:
    - ip: "127.0.0.1"
      port: 23790
minio:
  endpoint:
    ip: "127.0.0.1"
    port: 9000
  credentials:
    accessKeyId: "SOmGMHQdG0xf6BDmylne"
    secretAccessKey: "PSUgRBhKXf7s4qhR6T7bWqn9qPSQRB1vUnZ2TUPf"
