etcd:
  endpoints:
    - ip: "127.0.0.1"
      port: 23790
minio:
  endpoint:
    ip: "127.0.0.1"
    port: 9000
  credentials:
    accessKeyId: "lFYsJId1rOpeBFpV9fyO"
    secretAccessKey: "kf32kOuaqEkB5ULQExLldbno8Er3TKtPHpS1FQOh"
